### ISSUE TITLE
Need a Good Reference: Need help 

### ISSUE THREAD

**Issue by JibyJoseph** [JibyJoseph/Basic-Html-project#1]
I am learning **_responsive web design_** and it is hard find good reference material. I seem to be stuck with no idea what to do. I am _**moderately aware of HTML and CSS**_.  This is my first attempt at programming apart from some basic high school C++. I would be glad to receive any help. Tutorials _elucidating_ **_step by step_** processes preferred. Thank you.

**Comment by aks667** [comment]
Use google and youtube, you'll get it.
In any case, you want help, create an issue with a specific subject.
